title: Jon Carel Bunyi
description: Certified Database Management Analyst, Certified Industrial Engineer, Certified Lean Six Sigma Yellow Belt, Safety Officer II
show_downloads: true
theme: jekyll-theme-slate
